//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelekomNevaNetwork
{
    using System;
    using System.Collections.Generic;
    
    public partial class roles
    {
        public string role { get; set; }
        public Nullable<int> numRol { get; set; }
    }
}
